# Generated by Django 6.1.1 on 2026-09-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=150)),
                ('milestone_stat', models.CharField(help_text='e.g. 200,000+ YouTube Subscribers', max_length=100)),
                ('objective', models.TextField()),
                ('outcome', models.TextField()),
                ('support_areas', models.TextField(help_text='Newline-separated support areas delivered')),
                ('testimonial_quote', models.TextField(blank=True)),
                ('testimonial_author', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('business_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Business or Organization Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone_or_whatsapp', models.CharField(max_length=50, verbose_name='Phone or WhatsApp Number')),
                ('service_needed', models.CharField(choices=[('web_development', 'Website Design & Software Development'), ('social_media', 'Social Media Management'), ('digital_marketing', 'Business Promotion & Digital Marketing'), ('digital_branding', 'Digital Branding & Creative Content'), ('tech_training', 'Technology Training & Skill Development'), ('ict_supply', 'ICT Equipment & Tech Accessories Supply'), ('multiple', 'Multiple / Integrated Digital Services')], default='web_development', max_length=50, verbose_name='Service Needed')),
                ('project_description', models.TextField(verbose_name='Project Scope & Objectives')),
                ('estimated_budget', models.CharField(choices=[('undecided', 'Not yet decided / Flexible'), ('tier_1', '₦250,000 – ₦500,000'), ('tier_2', '₦500,000 – ₦1,500,000'), ('tier_3', '₦1,500,000 – ₦3,500,000'), ('tier_4', '₦3,500,000+ (Enterprise Scope)')], default='tier_1', max_length=50, verbose_name='Estimated Budget')),
                ('timeline', models.CharField(choices=[('immediate', 'Immediately (Within 1-2 weeks)'), ('normal', 'Standard (2-4 weeks)'), ('quarter', 'Upcoming Quarter / 1-3 months'), ('exploring', 'Just exploring possibilities')], default='normal', max_length=50, verbose_name='Expected Timeline')),
                ('status', models.CharField(choices=[('new', 'New Enquiry'), ('in_review', 'In Review'), ('contacted', 'Client Contacted'), ('closed', 'Closed / Converted')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('target_audience', models.CharField(help_text='e.g. SMEs, Startups, NGOs, Creators', max_length=255)),
                ('key_benefit', models.CharField(max_length=255)),
                ('capabilities_list', models.TextField(help_text='Newline-separated list of capabilities')),
                ('icon_svg', models.TextField(blank=True, help_text='Inline SVG code for custom icon')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
