# Generated by Django 6.1.1 on 2026-09-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_title_or_role', models.CharField(help_text="e.g. 'Lead Consultant & Managing Director'", max_length=150)),
                ('organization', models.CharField(help_text="e.g. 'Abuja Advisory Partners'", max_length=150)),
                ('service_category', models.CharField(help_text="e.g. 'Web Platform & Digital Strategy'", max_length=100)),
                ('quote', models.TextField(help_text='Client feedback / review text')),
                ('avatar_initial', models.CharField(default='MD', help_text="1-2 initials displayed when avatar image is not uploaded (e.g. 'MB')", max_length=5)),
                ('avatar_image', models.ImageField(blank=True, help_text='Optional client photo', null=True, upload_to='testimonials/avatars/')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Star rating from 1 to 5')),
                ('verified', models.BooleanField(default=True, help_text='Show verified client badge')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display priority in the carousel (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('author_name', models.CharField(default='Mark Digital Team', max_length=150)),
                ('excerpt', models.TextField(help_text='Brief summary shown on blog preview cards and search results')),
                ('content', models.TextField(help_text='Main article content (HTML or plain text supported)')),
                ('read_time', models.CharField(default='5 min read', help_text="e.g. '4 min read'", max_length=50)),
                ('featured_image', models.ImageField(blank=True, help_text='Recommended size: 1200x675px (16:9 ratio)', null=True, upload_to='blog/images/%Y/%m/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Accessible description of the image', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Pin this article as the hero highlight on the blog page')),
                ('publish_date', models.DateTimeField(blank=True, help_text='Publication date shown to visitors', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (defaults to post title if blank)', max_length=160)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (defaults to excerpt if blank)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-featured', '-publish_date', '-created_at'],
            },
        ),
    ]
