# Generated by Django 6.1.1 on 2026-09-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogcategory_testimonial_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('role_or_title', models.CharField(default='Technical Contributor', help_text="e.g. 'Lead Systems Engineer', 'Managing Director', 'Growth Strategist'", max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short bio shown on article pages and author bylines')),
                ('avatar_image', models.ImageField(blank=True, help_text='Author profile photo', null=True, upload_to='blog/authors/')),
                ('avatar_initial', models.CharField(default='MD', help_text='1-2 initials displayed when avatar image is not uploaded', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='Mark Digital Team', help_text='Fallback author display name', max_length=150),
        ),
        migrations.CreateModel(
            name='AuthorSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'X / Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('website', 'Personal / Portfolio Website'), ('email', 'Email Address')], max_length=30)),
                ('url', models.CharField(help_text="Full URL (e.g. 'https://linkedin.com/in/username') or email with 'mailto:'", max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.blogauthor')),
            ],
            options={
                'verbose_name': 'Author Social Media Link',
                'verbose_name_plural': 'Author Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Select dynamic author from admin panel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogauthor'),
        ),
    ]
