# Generated by Django 6.1.1 on 2026-09-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogauthor_alter_blogpost_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthor',
            name='avatar_initial',
            field=models.CharField(blank=True, default='', help_text='1-2 initials displayed when avatar image is not uploaded (auto-computed from name if left blank)', max_length=5),
        ),
    ]
