"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')
load_dotenv(BASE_DIR.parent / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-$9+1-91d!@ix6uy^b$1njegw+z+3plg&+(r*c^9^y#e41f(!tu')

# In production on Railway, set DEBUG=False in Railway Variables.
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*, .railway.app, .up.railway.app, localhost, 127.0.0.1').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://*.up.railway.app',
    'https://website-production-031c.up.railway.app',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

WHITENOISE_MANIFEST_STRICT = False


# Media files (User uploads for Blog featured images, testimonials, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration (for quote notifications to Gmail)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'markdigitalserviceslimited@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
NOTIFICATION_EMAIL = os.environ.get('NOTIFICATION_EMAIL', 'markdigitalserviceslimited@gmail.com')

# Company Information & External Constants (from .env)
COMPANY_NAME = os.environ.get('COMPANY_NAME', 'Mark Digital Services LTD')
COMPANY_LEGAL_ENTITY = os.environ.get('COMPANY_LEGAL_ENTITY', 'Private Company Limited by Shares')
COMPANY_DIRECTOR = os.environ.get('COMPANY_DIRECTOR', 'Akor Mark Akoji')
COMPANY_OFFICE_ADDRESS = os.environ.get('COMPANY_OFFICE_ADDRESS', '2, Rock Garden Avenue, Along Ganaja Road, Kogi State, Nigeria')
COMPANY_PHONE = os.environ.get('COMPANY_PHONE', '+234 811 789 7778')
COMPANY_PHONE_RAW = os.environ.get('COMPANY_PHONE_RAW', '2348117897778')
COMPANY_WHATSAPP = os.environ.get('COMPANY_WHATSAPP', '+234 811 789 7778')
COMPANY_WHATSAPP_URL = os.environ.get('COMPANY_WHATSAPP_URL', 'https://wa.me/2348117897778?text=Hello%20Mark%20Digital%20Services%20LTD%2C%20I%20would%20like%20to%20discuss%20a%20project.')
COMPANY_EMAIL = os.environ.get('COMPANY_EMAIL', 'markdigitalserviceslimited@gmail.com')
LINKEDIN_URL = os.environ.get('LINKEDIN_URL', 'https://www.linkedin.com/company/mdg-ltd/')
FACEBOOK_URL = os.environ.get('FACEBOOK_URL', 'https://web.facebook.com/mark.akor.210789/')
WORKING_HOURS_WEEKDAY = os.environ.get('WORKING_HOURS_WEEKDAY', 'Monday – Friday: 9:00 AM – 5:00 PM WAT')
WORKING_HOURS_WEEKEND = os.environ.get('WORKING_HOURS_WEEKEND', 'Saturday: 10:00 AM – 2:00 PM WAT')
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')

